author           = Nathan, Napiophelios
#depends          = bucket,default,vessels,stairs, placeable_buckets, ia_util
depends          = bucket,default,vessels,stairs, placeable_buckets, ia_util
description      = Adds a juice press and two juice storage containers. Most fruits and several veggies can be juiced. The resulting drinks can be 'ate' to gain health, or if you are using the thirsty mod, to regain hydration.
name             = drinks
optional_depends = hunger,thirsty,plantlife,farming_plus,crops,farming,minetest_doc_modpack,fruit,ethereal, technic,hunger_ng
title            = IA Drinks
